### ISSUE TITLE
ProxyClient发起的http-request中，header里少了透明代理相关的键值对

### ISSUE THREAD

**Issue by rafw** [GameXG/ProxyClient#13]
func main() {
	p, err := proxyclient.NewProxyClient("http://31.145.83.198:8080") // 网上找的一个免费的透明HTTP代理，有时候无法访问
	if err != nil {
		panic(err)
	}

	t := time.Now()
	c, err := p.Dial("tcp", "azenv.net:80")
	if err != nil {
		panic(err)
	}
	fmt.Println("连接耗时：", time.Now().Sub(t))

	if _, err := c.Write([]byte("GET / HTTP/1.0\r\nHOST:azenv.net\r\n\r\n")); err != nil {
		panic(err)
	}

	b := make([]byte, 2048)

	if n, err := c.Read(b); err != nil {
		panic(err)
	} else {
		fmt.Print(string(b[:n]))
	}

	c.Close()
}

31.145.83.198:8080通过多个提供Proxy Check服务的网站都可以识别出是透明代理，用标准库的HTTP设置HTTP代理的方式编程和发起请求，在HTTP服务端也可以看到多个透明代理添加的HTTP HEADER，比如“VIA”等，然鹅，用上述使用了ProxyClient代码访问时，却丢失了“VIA”等。请问，这个是否是ProxyClient的疏漏？

**Comment by GameXG** [comment]
出故障的这种代理是不支持 CONNECT 类型的请求，也就是无法兼容 net.Dialer 接口。proxyClient 目前对外提供的是
net.Dialer 接口，所以无法支持这种代理。
这种代理如果映射到 go 的话是 http.RoundTripper 接口(也就是只支持http协议)，目前 proxyClient
没对外提供这种接口。

另外如果确认是透明代理，那么实际是不需要 proxyClient的，它基本等于这种：

c,err:=net.Dial("tcp",代理服务器地址)

if _, err := c.Write([]byte("GET /
HTTP/1.0\r\nHOST:azenv.net\r\n\r\n")); err != nil {
	panic(err)
}

b := make([]byte, 2048)

if n, err := c.Read(b); err != nil {
	panic(err)
} else {
	fmt.Print(string(b[:n]))
}



rafael w <notifications@github.com>于2017年5月23日周二 下午5:13写道：
