### ISSUE TITLE
这个代理库的客户端能否用于开发独立的HTTP/SOCKS代理客户端软件？

### ISSUE THREAD

**Issue by rafw** [GameXG/ProxyClient#14]
我看了客户端的Demo，貌似只能用于Golang项目内部自行通过各种代理协议的服务器进行网络访问。

但是，能否像shadowsocks的客户端那样，通过SOCKS5协议为本地应用提供socks5代理服务器，且墙外的server提供墙外转发？

**Comment by GameXG** [comment]
https://github.com/GameXG/TcpRoute2 就是。

rafael w <notifications@github.com>于2017年5月23日周二 下午5:43写道：
