### ISSUE TITLE
socks4 握手都不对,少一个字节,

### ISSUE THREAD

**Issue by f4nff** [GameXG/ProxyClient#16]
socks4 握手都不对,少一个字节,

**Comment by GameXG** [comment]
具体指的是？

**Comment by f4nff** [comment]
https://www.openssh.com/txt/socks4.protocol

![032829](https://user-images.githubusercontent.com/19538878/31311158-d4d3e3b0-abd8-11e7-85ee-0e2d7625e0ab.png)


04 01             >>  固定 2字节
05 00              >> 端口 2字节
68 9B C8 D6    >>ip地址 4字节
 00                   >> 填充 1字节


少了最后的00字节.
我是拿 WLsoft.exe 测试的.你自己抓包看看

**Comment by f4nff** [comment]
VN is the SOCKS protocol version number and should be 4. CD is the
SOCKS command code and should be 1 for CONNECT request. NULL is a byte
of all zero bits.

null 你这里没有,,,

**Comment by f4nff** [comment]
好像还有点问题,你这个改之后,我可以再测下

**Comment by GameXG** [comment]
现在应该可以了。

**Comment by f4nff** [comment]
good

2017-10-08 16:35 GMT+08:00 GameXG <notifications@github.com>:
