### ISSUE TITLE
初学请教，http代理测试出现错误

### ISSUE THREAD

**Issue by zqzgit** [GameXG/ProxyClient#18]
无法连接代理服务器 127.0.0.1:7777 ，错误：dial tcp :0->127.0.0.1:7777: connectex: No connection could be made because the target machine actively refused it.
连接耗时： 1.0170582s

**Comment by GameXG** [comment]
127.0.0.1:7777 端口未开放，要么是 http代理服务器未启动，要么是地址填错了。
